### PR TITLE
Improved Readme so begginer can also use easily.

### PR DESCRIPTION
**Pull request by VishvajeetRamanuj**
When I want to use this program. I has to spend more then 2 hour for finding how can I run example. For saving time of other people who are relatively new like me. I make some changes to the instructions.
Thank you

### CODE REVIEW

**Review by infa-jowoods — COMMENTED** [review]
This is an excellent idea.

**Comment by dsprenkels** [comment]
Thank you for this patch!

Sorry for the enormous delay!

**Review by dsprenkels — APPROVED** [review]
Looks good to me! :)

**Comment by dsprenkels** [comment]
At the moment, there seems to be something going on which prevents the Travis status updates to come through. I will try to merge this ASAP.

**Comment by dsprenkels** [comment]
> 
> 
> At the moment, there seems to be something going on which prevents the Travis status updates to come through. I will try to merge this ASAP.

I removed the Travis requirement for now, until this is fixed. (<https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154>)

**Pull request merged**
